name: publish

on:
  push:
    tags:
      - '*'

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the hello-world Docker image
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      run: |
        docker build . --tag ghcr.io/${{ github.repository }}:latest --tag ghcr.io/${{ github.repository }}:$RELEASE_VERSION
        docker run ghcr.io/${{ github.repository }}:latest
        docker push --all-tags ghcr.io/${{ github.repository }}

